-- Create the crime_reports table
CREATE TABLE crime_reports
             (
                          incident_number VARCHAR(255) PRIMARY KEY,
                          highest_offense_description TEXT,
                          highest_offense_code VARCHAR(255),
                          family_violence      CHAR(1),
                          occurred_date_time TIMESTAMP,
                          occurred_date DATE,
                          occurred_time TIME,
                          report_date_time TIMESTAMP,
                          report_date DATE,
                          report_time TIME,
                          location_type TEXT,
                          address TEXT,
                          zip_code         VARCHAR(10),
                          council_district INT,
                          apd_sector       VARCHAR(10),
                          apd_district     VARCHAR(10),
                          pra              VARCHAR(10),
                          census_tract     VARCHAR(20),
                          clearance_status VARCHAR(50),
                          clearance_date   DATE,
                          ucr_category     VARCHAR(50),
                          category_description TEXT,
                          x_coordinate DOUBLE,
                          y_coordinate DOUBLE,
                          latitude DOUBLE,
                          longitude DOUBLE,
                          location geometry(point, 4326)
             );
